# 마이너리그 시즌 별 데이터 불러오기

In [3]:
import pandas as pd
import numpy as np


#minor = pd.read_excel("./103_pre.xlsx", engine = "openpyxl")
#minor = pd.read_excel("./103_pre2.xlsx", engine = "openpyxl")

#minor1 = pd.read_csv('./마이너리그시즌데이터/minor1.csv')
#minor2 = pd.read_csv('./마이너리그시즌데이터/minor2.csv')
#minor3 = pd.read_csv('./마이너리그시즌데이터/minor3.csv')

In [66]:
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings(action='ignore')

minor1 = pd.read_csv("./마이너타자1.csv")
minor2 = pd.read_csv("./마이너타자2.csv")
minor3 = pd.read_csv("./마이너타자3.csv")

minor_batter = pd.read_csv("./외국인타자_마이너성적.csv")

In [67]:
temp_columns1 = set(minor1.columns) & set(minor2.columns)

temp1 = pd.merge(minor1, minor2, on = list(temp_columns1))

temp_columns2 = set(temp1.columns) & set(minor3.columns)

temp2 = pd.merge(temp1, minor3, on = list(temp_columns2))

merge_minor_df = temp2.copy()

minor_columns = ["Season","G","PA","AB","R","H","2B","3B","HR","RBI","SB","CS","BB","SO","AVG","OBP","SLG","OPS","GDP","HBP","SH","SF","IBB"]
minor_columns2 = ["G","PA","AB","R","H","2B","3B","HR","RBI","SB","CS","BB","SO","AVG","OBP","SLG","OPS","GDP","HBP","SH","SF","IBB"]

merge_minor_df = merge_minor_df[minor_columns]
merge_minor_df["TB"] = merge_minor_df["H"] - (merge_minor_df["2B"] + merge_minor_df["3B"] + merge_minor_df["HR"]) +\
                        merge_minor_df["2B"] * 2 + merge_minor_df["3B"] * 3 + merge_minor_df["HR"] * 4

merge_minor_df = merge_minor_df.sort_values(by = "Season").reset_index(drop = True)

merge_minor_df

,Season,G,PA,AB,R,H,2B,3B,HR,RBI,...,AVG,OBP,SLG,OPS,GDP,HBP,SH,SF,IBB,TB
0,2013,37,141,124,19,42,10,1,2,25,...,0.338710,0.404255,0.483871,0.888126,0,1,0,2,1,60
1,2013,45,198,173,23,40,13,1,3,22,...,0.231214,0.318182,0.369942,0.688124,2,1,0,2,2,64
2,2013,136,579,506,61,139,33,5,8,49,...,0.274704,0.362694,0.407115,0.769809,8,6,0,2,0,206
3,2013,103,345,304,36,97,27,3,3,32,...,0.319079,0.380117,0.457237,0.837354,6,4,3,5,2,139
4,2013,52,201,177,28,39,5,0,5,15,...,0.220339,0.306533,0.333333,0.639866,2,0,2,0,1,59
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4612,2022,67,267,244,27,61,12,4,5,34,...,0.250000,0.303371,0.393443,0.696813,3,1,0,3,0,96
4613,2022,135,604,545,81,152,31,9,16,67,...,0.278899,0.344371,0.456881,0.801252,6,10,0,3,3,249
4614,2022,127,520,452,55,99,26,4,16,72,...,0.219027,0.304432,0.400442,0.704874,7,10,1,8,0,181
4615,2022,50,202,170,20,54,8,1,8,30,...,0.317647,0.420792,0.517647,0.938439,5,4,0,1,1,88
4616,2022,80,375,346,77,105,12,4,13,48,...,0.303468,0.354667,0.473988,0.828655,1,6,0,1,1,164

In [90]:
merge_minor_df[merge_minor_df["Season"] == season][minor_columns]

,Season,G,PA,AB,R,H,2B,3B,HR,RBI,...,SO,AVG,OBP,SLG,OPS,GDP,HBP,SH,SF,IBB
4034,2022,35,130,120,14,25,7,0,1,10,...,33,0.208333,0.253846,0.291667,0.545513,2,2,0,2,0
4035,2022,68,307,279,49,79,16,6,10,38,...,73,0.283154,0.348534,0.491039,0.839574,2,2,0,0,1
4036,2022,99,429,386,57,100,16,0,19,50,...,100,0.259067,0.329439,0.448187,0.777626,2,7,1,1,0
4037,2022,72,306,279,33,75,15,0,7,43,...,41,0.268817,0.311475,0.397849,0.709325,10,0,1,6,0
4038,2022,66,265,232,26,44,8,0,6,35,...,92,0.189655,0.283019,0.301724,0.584743,3,6,0,2,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4612,2022,67,267,244,27,61,12,4,5,34,...,59,0.250000,0.303371,0.393443,0.696813,3,1,0,3,0
4613,2022,135,604,545,81,152,31,9,16,67,...,136,0.278899,0.344371,0.456881,0.801252,6,10,0,3,3
4614,2022,127,520,452,55,99,26,4,16,72,...,135,0.219027,0.304432,0.400442,0.704874,7,10,1,8,0
4615,2022,50,202,170,20,54,8,1,8,30,...,48,0.317647,0.420792,0.517647,0.938439,5,4,0,1,1
4616,2022,80,375,346,77,105,12,4,13,48,...,95,0.303468,0.354667,0.473988,0.828655,1,6,0,1,1

In [100]:
from sklearn.preprocessing import StandardScaler

ss = StandardScaler()

ss_df = pd.DataFrame(columns=minor_columns)
seasons = [2013,2014,2015,2016,2017,2018,2019,2021]

for season in seasons:
    
    temp1 = merge_minor_df[merge_minor_df["Season"] == season]
    ss.fit(temp1[minor_columns])
    temp2 = ss.transform(minor_batter[minor_batter["Season"] == season][minor_columns])
    temp2 = pd.DataFrame(temp2, columns=minor_columns)
    ss_df = ss_df.append(temp2[minor_columns])

In [101]:
ss_df

,Season,G,PA,AB,R,H,2B,3B,HR,RBI,...,SO,AVG,OBP,SLG,OPS,GDP,HBP,SH,SF,IBB
0,0.0,1.01238,1.11366,1.034952,1.165216,0.952396,0.828824,-0.406785,1.003549,0.969044,...,0.464343,0.083108,0.427129,0.19727,0.301865,0.253353,0.06269,-0.785232,1.784849,-0.721945
1,0.0,-1.723856,-1.573108,-1.524695,-1.289978,-1.341288,-1.135063,-0.879149,-0.452164,-0.627925,...,-1.565487,0.681964,-0.785851,1.049354,0.438993,-0.237549,-1.077203,-0.785232,-0.194114,-0.721945
2,0.0,-0.748875,-0.682467,-0.758485,-0.610882,-0.905778,-0.766835,-0.879149,-0.2702,-0.67944,...,-0.452354,-0.939938,-0.246748,-0.557434,-0.486626,0.007902,-1.077203,-0.785232,1.290109,0.161815
3,0.0,1.263988,1.158192,1.21177,2.105503,1.649212,1.810767,1.482673,1.003549,1.329649,...,1.937607,1.18101,0.786531,1.12239,1.090355,0.007902,-0.697239,-0.396139,1.290109,1.045575
4,0.0,0.634968,0.876156,0.900234,1.217454,1.155634,1.688024,0.06558,0.457656,1.63874,...,-0.190441,0.831678,0.449592,0.647657,0.618975,-0.237549,0.442655,-0.785232,2.774331,3.696854
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5,0.0,0.613873,0.738645,0.586757,1.358929,0.603075,-0.362976,1.10357,0.475149,0.472237,...,0.448507,0.284175,1.027181,0.122011,0.446248,0.508858,2.148787,-0.487296,-1.098004,0.77438
6,0.0,-0.486685,-0.389728,-0.371489,-0.575362,-0.489745,-0.362976,0.448325,-0.694323,-0.712259,...,0.022885,-0.474839,-0.411105,-0.594888,-0.581003,-0.671003,-0.109503,-0.487296,-0.496856,-0.54981
7,0.0,0.967624,1.25068,1.129762,2.144735,1.258767,1.935871,-0.206919,1.811687,1.995161,...,1.79631,0.574386,0.921425,1.067918,1.106624,1.098789,1.301929,-0.487296,0.104293,-0.54981
8,0.0,1.753737,1.648929,1.704709,1.419376,1.404476,0.709819,0.448325,0.141014,1.205497,...,1.33522,-0.073008,-0.49571,-0.55506,-0.581003,0.213893,0.737356,-0.487296,2.508888,-0.54981
9,0.0,-0.80113,-0.863835,-0.925141,-0.514916,-0.781164,-0.362976,0.448325,-0.86139,-0.712259,...,-0.757422,0.261851,0.66761,0.062269,0.277486,-0.376038,-0.109503,-0.487296,0.705442,-0.54981

In [102]:
ss_df = ss_df.reset_index(drop=True)
ss_df

,Season,G,PA,AB,R,H,2B,3B,HR,RBI,...,SO,AVG,OBP,SLG,OPS,GDP,HBP,SH,SF,IBB
0,0.0,1.01238,1.11366,1.034952,1.165216,0.952396,0.828824,-0.406785,1.003549,0.969044,...,0.464343,0.083108,0.427129,0.19727,0.301865,0.253353,0.06269,-0.785232,1.784849,-0.721945
1,0.0,-1.723856,-1.573108,-1.524695,-1.289978,-1.341288,-1.135063,-0.879149,-0.452164,-0.627925,...,-1.565487,0.681964,-0.785851,1.049354,0.438993,-0.237549,-1.077203,-0.785232,-0.194114,-0.721945
2,0.0,-0.748875,-0.682467,-0.758485,-0.610882,-0.905778,-0.766835,-0.879149,-0.2702,-0.67944,...,-0.452354,-0.939938,-0.246748,-0.557434,-0.486626,0.007902,-1.077203,-0.785232,1.290109,0.161815
3,0.0,1.263988,1.158192,1.21177,2.105503,1.649212,1.810767,1.482673,1.003549,1.329649,...,1.937607,1.18101,0.786531,1.12239,1.090355,0.007902,-0.697239,-0.396139,1.290109,1.045575
4,0.0,0.634968,0.876156,0.900234,1.217454,1.155634,1.688024,0.06558,0.457656,1.63874,...,-0.190441,0.831678,0.449592,0.647657,0.618975,-0.237549,0.442655,-0.785232,2.774331,3.696854
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
71,0.0,0.613873,0.738645,0.586757,1.358929,0.603075,-0.362976,1.10357,0.475149,0.472237,...,0.448507,0.284175,1.027181,0.122011,0.446248,0.508858,2.148787,-0.487296,-1.098004,0.77438
72,0.0,-0.486685,-0.389728,-0.371489,-0.575362,-0.489745,-0.362976,0.448325,-0.694323,-0.712259,...,0.022885,-0.474839,-0.411105,-0.594888,-0.581003,-0.671003,-0.109503,-0.487296,-0.496856,-0.54981
73,0.0,0.967624,1.25068,1.129762,2.144735,1.258767,1.935871,-0.206919,1.811687,1.995161,...,1.79631,0.574386,0.921425,1.067918,1.106624,1.098789,1.301929,-0.487296,0.104293,-0.54981
74,0.0,1.753737,1.648929,1.704709,1.419376,1.404476,0.709819,0.448325,0.141014,1.205497,...,1.33522,-0.073008,-0.49571,-0.55506,-0.581003,0.213893,0.737356,-0.487296,2.508888,-0.54981
75,0.0,-0.80113,-0.863835,-0.925141,-0.514916,-0.781164,-0.362976,0.448325,-0.86139,-0.712259,...,-0.757422,0.261851,0.66761,0.062269,0.277486,-0.376038,-0.109503,-0.487296,0.705442,-0.54981

In [112]:
X = ss_df[minor_columns2]
X = X.astype(float)
y = minor_batter["재계약"]

In [104]:
# 기본패키지

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
plt.rcParams['font.family'] = 'Malgun Gothic'
import seaborn as sns
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from collections import Counter

# 모델
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
from xgboost import XGBClassifier
from lightgbm import LGBMClassifier
from catboost import CatBoostClassifier

# 모델
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestRegressor
from xgboost import XGBRegressor
from lightgbm import LGBMRegressor
from catboost import CatBoostRegressor

# 검증
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import cross_val_predict
from sklearn.model_selection import StratifiedKFold
from sklearn.metrics import confusion_matrix, classification_report
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, roc_auc_score
from sklearn.metrics import roc_curve, auc
#pd.set_option('display.max_columns', None) # 컬럼 수가 많으므로 요약되어 표시되지 않게 함
import warnings
warnings.filterwarnings(action='ignore')

In [105]:
lr = LogisticRegression()
svc = SVC()
rf = RandomForestClassifier()
xgb = XGBClassifier()
lgbm = LGBMClassifier()
cat = CatBoostClassifier(verbose=0)

In [114]:
print(f'lr : {cross_val_score(lr, X,y, cv=5).mean()}')
print(f'svc : {cross_val_score(svc, X,y, cv=5).mean()}')
print(f'rf : {cross_val_score(rf, X,y, cv=5).mean()}')
print(f'cat : {cross_val_score(cat, X,y, cv=5).mean()}')
print(f'xgb : {cross_val_score(xgb, X,y, cv=5).mean()}')
print(f'lgbm: {cross_val_score(lgbm, X,y, cv=5).mean()}')

lr : 0.6583333333333333
svc : 0.6325000000000001
rf : 0.6191666666666665
cat : 0.5933333333333333
xgb : 0.5650000000000001
lgbm: 0.6325000000000001

In [115]:
print(f'lr : {cross_val_score(lr, X,y, cv=5,scoring="roc_auc").mean()}')
print(f'svc : {cross_val_score(svc, X,y, cv=5,scoring="roc_auc").mean()}')
print(f'rf : {cross_val_score(rf, X,y, cv=5,scoring="roc_auc").mean()}')
print(f'cat : {cross_val_score(cat, X,y, cv=5,scoring="roc_auc").mean()}')
print(f'xgb : {cross_val_score(xgb, X,y, cv=5,scoring="roc_auc").mean()}')
print(f'lgbm: {cross_val_score(lgbm, X,y, cv=5,scoring="roc_auc").mean()}')

lr : 0.6453333333333333
svc : 0.6747407407407409
rf : 0.5822592592592593
cat : 0.6045185185185185
xgb : 0.5525185185185186
lgbm: 0.666962962962963

In [117]:
print(f'lr : {cross_val_score(lr, X,y, cv=5,scoring="precision").mean()}')
print(f'svc : {cross_val_score(svc, X,y, cv=5,scoring="precision").mean()}')
print(f'rf : {cross_val_score(rf, X,y, cv=5,scoring="precision").mean()}')
print(f'cat : {cross_val_score(cat, X,y, cv=5,scoring="precision").mean()}')
print(f'xgb : {cross_val_score(xgb, X,y, cv=5,scoring="precision").mean()}')
print(f'lgbm: {cross_val_score(lgbm, X,y, cv=5,scoring="precision").mean()}')

lr : 0.5466666666666666
svc : 0.48
rf : 0.6357142857142858
cat : 0.5166666666666666
xgb : 0.38
lgbm: 0.4666666666666666

In [123]:
print(y.value_counts())
print(f'28/76 = {28/76}')
print(f'48/76 = {48/76}')

0    48
1    28
Name: 재계약, dtype: int64
28/76 = 0.3684210526315789
48/76 = 0.631578947368421

In [124]:
from sklearn.naive_bayes import GaussianNB

nb = GaussianNB()
cross_val_score(nb, X,y, cv=5, scoring="precision").mean()

0.464047619047619

#  메이저리그 기록 표준화

In [203]:
korea_major = pd.read_csv("./외국인타자MLB배럴성적2.csv")
korea_major = korea_major.iloc[:-5]
korea_major = korea_major.sort_values(by = "Season", ascending = True).reset_index(drop = True)

major = pd.read_csv("./1522메이저타자.csv")
major = major.rename(columns = {"year" : "Season"})
major = major.sort_values(by = "Season", ascending=True).reset_index(drop = True)

In [205]:
major

,last_name,first_name,player_id,Season,Age,Pitches,Batted Balls,Barrels,Barrel%,Barrel/PA,...,XBA,XSLG,WOBA,XWOBA,XWOBACON,Exit Velocity,Launch Angle,Sweet Spot %,HardHit%,Max EV
0,Conforto,Michael,624424,2015,22,743,137,13,9.5,6.701031,...,0.284,0.539,0.359,0.382,0.451,92.3,13.4,33.6,47.4,102.522868
1,Burns,Billy,542993,2015,25,1943,442,2,0.5,0.360360,...,0.239,0.288,0.317,0.260,0.278,83.2,8.1,26.9,14.7,92.105101
2,Beckham,Tim,542921,2015,25,899,138,8,5.8,3.587444,...,0.220,0.359,0.300,0.282,0.376,87.0,8.8,33.3,37.7,99.361280
3,Santana,Danny,542454,2015,24,940,200,1,0.5,0.361011,...,0.200,0.248,0.231,0.214,0.271,86.1,5.9,22.5,23.5,96.129559
4,Villar,Jonathan,542340,2015,24,501,89,3,3.4,2.343750,...,0.247,0.357,0.328,0.295,0.350,90.7,2.8,23.6,38.2,100.806731
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3454,Nootbaar,Lars,663457,2022,24,1389,224,27,12.1,7.780980,...,0.247,0.414,0.342,0.346,0.377,91.7,10.7,30.4,46.0,101.790400
3455,Nevin,Tyler,663527,2022,25,793,114,4,3.5,2.173913,...,0.212,0.324,0.261,0.291,0.324,87.3,17.7,34.2,37.7,98.356865
3456,Hoerner,Nico,663538,2022,25,1831,426,11,2.6,2.127660,...,0.270,0.367,0.320,0.301,0.314,87.2,10.6,32.4,33.5,97.678972
3457,Garcia,Dermis,660650,2022,24,535,61,8,13.1,6.400000,...,0.167,0.324,0.285,0.244,0.398,86.5,12.2,27.9,42.6,100.773492
3458,Pujols,Albert,405395,2022,42,1385,258,31,12.0,8.831909,...,0.262,0.499,0.380,0.365,0.395,91.2,16.4,34.5,47.3,102.064437

In [177]:
columns = list(korea_major.columns)
columns.remove("영문이름")
columns.remove("이름")
columns.remove("구단")

columns1 = columns.copy()
columns1.remove("재계약")

In [178]:
korea_major["Season"].value_counts()

2019    13
2018     8
2021     8
2015     6
2016     5
2017     5
2020     1
Name: Season, dtype: int64

In [179]:
from sklearn.preprocessing import StandardScaler

ss = StandardScaler()

ss_df = pd.DataFrame(columns=columns1)

for season in range(2015,2021+1):
    temp1 = major[major["Season"] == season]
    #temp2 = ss.fit_transform(temp1[columns])
    ss.fit(temp1[columns1])
    #print(ss.transform(temp1[column_orders]))
    temp2 = ss.transform(korea_major[korea_major["Season"] == season][columns1])
    temp2 = pd.DataFrame(temp2, columns = columns1)
    ss_df = ss_df.append(temp2[columns1])

ss_df = ss_df.reset_index(drop = True)

In [180]:
X = ss_df.drop(columns = ["Season"])
X = X.astype(float)
y = korea_major["재계약"]

In [181]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
from xgboost import XGBClassifier
from lightgbm import LGBMClassifier
from catboost import CatBoostClassifier

# 모델
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestRegressor
from xgboost import XGBRegressor
from lightgbm import LGBMRegressor
from catboost import CatBoostRegressor

# 검증
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import cross_val_predict
from sklearn.model_selection import StratifiedKFold
from sklearn.metrics import confusion_matrix, classification_report
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, roc_auc_score
from sklearn.metrics import roc_curve, auc
#pd.set_option('display.max_columns', None) # 컬럼 수가 많으므로 요약되어 표시되지 않게 함
import warnings
warnings.filterwarnings(action='ignore')

In [182]:
print(f'lr : {cross_val_score(lr, X,y, cv=5).mean()}')
print(f'svc : {cross_val_score(svc, X,y, cv=5).mean()}')
print(f'rf : {cross_val_score(rf, X,y, cv=5).mean()}')
print(f'cat : {cross_val_score(cat, X,y, cv=5).mean()}')
print(f'xgb : {cross_val_score(xgb, X,y, cv=5).mean()}')
print(f'lgbm: {cross_val_score(lgbm, X,y, cv=5).mean()}')

lr : 0.571111111111111
svc : 0.6533333333333332
rf : 0.6088888888888888
cat : 0.5866666666666666
xgb : 0.5444444444444445
lgbm: 0.6533333333333332

In [183]:
print(f'lr : {cross_val_score(lr, X,y, cv=5,scoring="roc_auc").mean()}')
print(f'svc : {cross_val_score(svc, X,y, cv=5,scoring="roc_auc").mean()}')
print(f'rf : {cross_val_score(rf, X,y, cv=5,scoring="roc_auc").mean()}')
print(f'cat : {cross_val_score(cat, X,y, cv=5,scoring="roc_auc").mean()}')
print(f'xgb : {cross_val_score(xgb, X,y, cv=5,scoring="roc_auc").mean()}')
print(f'lgbm: {cross_val_score(lgbm, X,y, cv=5,scoring="roc_auc").mean()}')

lr : 0.5791666666666667
svc : 0.43194444444444446
rf : 0.45555555555555555
cat : 0.46805555555555556
xgb : 0.34305555555555556
lgbm: 0.5

In [184]:
print(f'lr : {cross_val_score(lr, X,y, cv=5,scoring="precision").mean()}')
print(f'svc : {cross_val_score(svc, X,y, cv=5,scoring="precision").mean()}')
print(f'rf : {cross_val_score(rf, X,y, cv=5,scoring="precision").mean()}')
print(f'cat : {cross_val_score(cat, X,y, cv=5,scoring="precision").mean()}')
print(f'xgb : {cross_val_score(xgb, X,y, cv=5,scoring="precision").mean()}')
print(f'lgbm: {cross_val_score(lgbm, X,y, cv=5,scoring="precision").mean()}')

lr : 0.21333333333333332
svc : 0.0
rf : 0.35
cat : 0.06666666666666667
xgb : 0.13333333333333333
lgbm: 0.0

In [197]:
korea_major2 = pd.read_csv("./외국인타자MLB배럴성적2.csv")
korea_major2 = korea_major2.iloc[:-5].reset_index(drop = True)
korea_major2.head()

,영문이름,이름,구단,재계약,Season,Age,Pitches,Batted Balls,Barrels,Barrel%,...,Launch Angle,Sweet Spot %,XBA,XSLG,WOBA,XWOBA,XWOBACON,HardHit%,K%,BB%
0,Daniel Casey Dorn,대니 돈,키움,1.0,2015,30,125,20,0,0.0,...,8.6,25.0,0.184,0.234,0.192,0.215,0.279,35.0,31.3,6.3
1,Hector Alexis Gomez,헥터 고메즈,SSG,0.0,2015,27,488,89,3,3.4,...,14.2,36.0,0.222,0.311,0.231,0.250,0.342,29.2,29.9,2.2
2,Wilin Arismendy Rosario,윌린 로사리오,한화,1.0,2015,26,859,177,8,4.5,...,5.8,26.0,0.231,0.354,0.303,0.269,0.340,33.9,23.1,3.3
3,Justin Adam Maxwell,저스틴 맥스웰,롯데,0.0,2015,31,1030,175,9,5.1,...,10.3,30.9,0.213,0.358,0.271,0.283,0.359,32.0,27.7,7.3
4,Xavier Ladel Scruggs,재비어 스크럭스,NC,1.0,2015,31,1030,175,9,5.1,...,10.3,30.9,0.213,0.358,0.271,0.283,0.359,32.0,27.7,7.3

In [198]:
X2 = korea_major2.drop(columns = ["영문이름", "이름", "구단","재계약","Season"])
X2 = X2.astype(float)
y2 = korea_major2["재계약"]

In [200]:
print(f'lr : {cross_val_score(lr, X2,y2, cv=5).mean()}')
print(f'svc : {cross_val_score(svc, X2,y2, cv=5).mean()}')
print(f'rf : {cross_val_score(rf, X2,y2, cv=5).mean()}')
print(f'cat : {cross_val_score(cat, X2,y2, cv=5).mean()}')
print(f'xgb : {cross_val_score(xgb, X2,y2, cv=5).mean()}')
print(f'lgbm: {cross_val_score(lgbm, X2,y2, cv=5).mean()}')

lr : 0.5511111111111111
svc : 0.6533333333333332
rf : 0.6755555555555556
cat : 0.6977777777777777
xgb : 0.611111111111111
lgbm: 0.6533333333333332

In [201]:
print(f'lr : {cross_val_score(lr, X2,y2, cv=5,scoring="roc_auc").mean()}')
print(f'svc : {cross_val_score(svc, X2,y2, cv=5,scoring="roc_auc").mean()}')
print(f'rf : {cross_val_score(rf, X2,y2, cv=5,scoring="roc_auc").mean()}')
print(f'cat : {cross_val_score(cat, X2,y2, cv=5,scoring="roc_auc").mean()}')
print(f'xgb : {cross_val_score(xgb, X2,y2, cv=5,scoring="roc_auc").mean()}')
print(f'lgbm: {cross_val_score(lgbm, X2,y2, cv=5,scoring="roc_auc").mean()}')

lr : 0.5875
svc : 0.548611111111111
rf : 0.5458333333333333
cat : 0.4958333333333333
xgb : 0.5236111111111111
lgbm: 0.5

In [202]:
print(f'lr : {cross_val_score(lr, X2,y2, cv=5,scoring="precision").mean()}')
print(f'svc : {cross_val_score(svc, X2,y2, cv=5,scoring="precision").mean()}')
print(f'rf : {cross_val_score(rf, X2,y2, cv=5,scoring="precision").mean()}')
print(f'cat : {cross_val_score(cat, X2,y2, cv=5,scoring="precision").mean()}')
print(f'xgb : {cross_val_score(xgb, X2,y2, cv=5,scoring="precision").mean()}')
print(f'lgbm: {cross_val_score(lgbm, X2,y2, cv=5,scoring="precision").mean()}')

lr : 0.3333333333333333
svc : 0.0
rf : 0.5
cat : 0.6
xgb : 0.54
lgbm: 0.0

In [93]:
cross_val_score(lr,X,y, cv = 5).mean()

0.6824175824175824

In [95]:
cross_val_score(lr,X,y, cv = 5, scoring="roc_auc").mean()

0.5205555555555555

In [96]:
cross_val_score(xgb,X,y, cv = 5).mean()

0.6989010989010989

In [97]:
cross_val_score(xgb,X,y, cv = 5, scoring="roc_auc").mean()

0.49499999999999994

In [98]:
cross_val_score(lgbm,X,y, cv = 5).mean()

0.6527472527472528

In [99]:
cross_val_score(lgbm,X,y, cv = 5, scoring="roc_auc").mean()

0.5061111111111111

In [100]:
cross_val_score(rf,X,y, cv = 5).mean()

0.7274725274725274

In [101]:
cross_val_score(rf,X,y, cv = 5, scoring="roc_auc").mean()

0.5747222222222221

In [105]:
cross_val_score(cat,X,y, cv = 5).mean()

0.7274725274725276

In [106]:
cross_val_score(cat,X,y, cv = 5, scoring="roc_auc").mean()

0.611111111111111